// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	updateFontSize: (size: number) => typedError<null, string>(__TAURI_INVOKE("update_font_size", { size })),
	getAppState: () => typedError<AppState, string>(__TAURI_INVOKE("get_app_state")),
	getNotesState: () => typedError<NotesState, string>(__TAURI_INVOKE("get_notes_state")),
	pickNotesFile: () => typedError<{
	path: string,
	title: string,
	content: string,
} | null, string>(__TAURI_INVOKE("pick_notes_file")),
	setActiveNotesFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_active_notes_file", { path })),
	closeNotesFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("close_notes_file", { path })),
	sendAudioBlob: (args: SendAudioBlobArgs) => typedError<null, string>(__TAURI_INVOKE("send_audio_blob", { args })),
	askAiText: (args: AskAiTextArgs) => typedError<null, string>(__TAURI_INVOKE("ask_ai_text", { args })),
	askAiScreen: () => typedError<null, string>(__TAURI_INVOKE("ask_ai_screen")),
	askAiSelectedText: () => typedError<null, string>(__TAURI_INVOKE("ask_ai_selected_text")),
	copyToClipboard: (args: CopyToClipboardArgs) => typedError<null, string>(__TAURI_INVOKE("copy_to_clipboard", { args })),
	testTriggerHotkey: (args: TestTriggerHotkeyArgs) => typedError<null, string>(__TAURI_INVOKE("test_trigger_hotkey", { args })),
};

/** Events */
export const events = {
	answerResult: makeEvent<AnswerResultPayload>("answer:result"),
	configError: makeEvent<ConfigErrorPayload>("config:error"),
	notesCycleTab: makeEvent<NotesCycleTabPayload>("notes:cycle-tab"),
	notesError: makeEvent<NotesErrorPayload>("notes:error"),
	notesToggleFind: makeEvent<NotesToggleFindPayload>("notes:toggle-find"),
	notesUpdate: makeEvent<NotesUpdatePayload>("notes:update"),
	qaError: makeEvent<QaErrorPayload>("qa:error"),
	qaRecordingEnded: makeEvent<RecordingEndedPayload>("qa:recording-ended"),
	transcriptResult: makeEvent<TranscriptResultPayload>("transcript:result"),
};

/* Types */
export type AnswerResultPayload = {
	text: string,
};

export type AppState = {
	fontSize: number,
	qaAvailable: boolean,
};

export type AskAiTextArgs = {
	prompt: string,
};

export type ConfigErrorPayload = {
	message: string,
};

export type CopyToClipboardArgs = {
	text: string,
};

export type NoteDocument = {
	path: string,
	title: string,
	content: string,
};

export type NotesCycleTabPayload = Record<string, never>;

export type NotesErrorPayload = {
	message: string,
};

export type NotesState = {
	documents: NoteDocument[],
	activePath: string | null,
	content: string | null,
	error: string | null,
};

export type NotesToggleFindPayload = Record<string, never>;

export type NotesUpdatePayload = {
	path: string,
	content: string,
};

export type PickNotesFileResponse = {
	path: string,
	title: string,
	content: string,
};

export type QaErrorPayload = {
	stage: string,
	message: string,
};

export type RecordingEndedPayload = {
	belowThreshold: boolean,
};

export type SendAudioBlobArgs = {
	bytes: number[],
};

export type TestTriggerHotkeyArgs = {
	hotkey: string,
	state: string,
};

export type TranscriptResultPayload = {
	text: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

